### ISSUE TITLE
I would to contribute with some mini projects 

### ISSUE THREAD

**Issue by iamakhileshmishra** [sakshi-choudhary/CoronaGo#8]
Is the Repository still accepting the PR for hacktoberfest if yes then please assign this issue under hacktoberfest accepted

**Comment by iamakhileshmishra** [comment]
Please add the label for hacktoberfest

**Comment by iamakhileshmishra** [comment]
I am going to add an option for a theme toggler on the website for dark/light. Is it ok ...?

**Comment by iamakhileshmishra** [comment]
@sakshi-choudhary  I have raised a PR please accept it under hacktoberfest-accepted tag. Thank you

**Comment by Hiresh23** [comment]
i would like to contribute to project
